// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_k6-tNwDXM4qd1B6iKkoyRLWWuRPeHgE',
    appId: '1:696184557049:web:0fa320a9865d8733fc0128',
    messagingSenderId: '696184557049',
    projectId: 'smarthomeguard-7dafd',
    authDomain: 'smarthomeguard-7dafd.firebaseapp.com',
    storageBucket: 'smarthomeguard-7dafd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yjCjaut_2n8ck8Ib3h5-c3i6qyP4NUE',
    appId: '1:696184557049:android:055089fb767574d9fc0128',
    messagingSenderId: '696184557049',
    projectId: 'smarthomeguard-7dafd',
    storageBucket: 'smarthomeguard-7dafd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx1SjIFWryFcH-nObhnuzd0fzkOqlwGNs',
    appId: '1:696184557049:ios:7c91a3215402b463fc0128',
    messagingSenderId: '696184557049',
    projectId: 'smarthomeguard-7dafd',
    storageBucket: 'smarthomeguard-7dafd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx1SjIFWryFcH-nObhnuzd0fzkOqlwGNs',
    appId: '1:696184557049:ios:7c91a3215402b463fc0128',
    messagingSenderId: '696184557049',
    projectId: 'smarthomeguard-7dafd',
    storageBucket: 'smarthomeguard-7dafd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_k6-tNwDXM4qd1B6iKkoyRLWWuRPeHgE',
    appId: '1:696184557049:web:5077057e5c341805fc0128',
    messagingSenderId: '696184557049',
    projectId: 'smarthomeguard-7dafd',
    authDomain: 'smarthomeguard-7dafd.firebaseapp.com',
    storageBucket: 'smarthomeguard-7dafd.firebasestorage.app',
  );
}
