import boto3
import json
import os
import base64
import uuid
from datetime import datetime

# Initialize AWS services
s3 = boto3.client('s3')
rekognition = boto3.client('rekognition')
dynamodb = boto3.resource('dynamodb')

# Environment variables
BUCKET_NAME = os.environ.get('BUCKET_NAME')
COLLECTION_ID = os.environ.get('COLLECTION_ID')
TABLE_USER_NAME = os.environ.get('TABLE_USER_NAME')

def lambda_handler(event, context):
    try:
        # Handle both Lambda Proxy Integration and Non-Proxy Integration
        if 'body' in event and isinstance(event['body'], str):
            body = json.loads(event['body'])
        else:
            body = event

        # Extract data from the Flutter HTTP request
        user_name = body.get('user_name')
        user_role = body.get('user_role', 'Undefined')
        base64_image = body.get('image')

        # Validate input
        if not user_name or not base64_image:
            return {
                'statusCode': 400,
                'headers': {'Access-Control-Allow-Origin': '*'},
                'body': json.dumps({'error': 'Missing user_name or image'})
            }

        # 1. Decode the base64 image back to bytes
        image_bytes = base64.b64decode(base64_image)
        
        # 2. Generate a unique path for the profile picture in S3
        timestamp = datetime.utcnow().isoformat()
        unique_id = str(uuid.uuid4())[:8] # Short unique ID to prevent overwriting
        safe_user_name = user_name.replace(' ', '_')
        image_key = f"profile_pictures/{safe_user_name}_{unique_id}.jpg"

        # 3. Upload the image to S3 bucket
        s3.put_object(
            Bucket=BUCKET_NAME,
            Key=image_key,
            Body=image_bytes,
            ContentType='image/jpeg'
        )

        # 4. Index the new face in AWS Rekognition
        index_response = rekognition.index_faces(
            CollectionId=COLLECTION_ID,
            Image={'S3Object': {'Bucket': BUCKET_NAME, 'Name': image_key}}, 
            ExternalImageId=safe_user_name[:90], # Rekognition has a limit on string length
            MaxFaces=1,
            QualityFilter='AUTO'
        )

        # Check if a face was actually detected in the uploaded image
        if not index_response.get('FaceRecords'):
            # If no face is detected, we can optionally delete the S3 image here
            return {
                'statusCode': 400,
                'headers': {'Access-Control-Allow-Origin': '*'},
                'body': json.dumps({'error': 'No face detected in the provided image. Please try another photo.'})
            }
        
        # Extract the new FaceID generated by Rekognition
        new_face_id = index_response['FaceRecords'][0]['Face']['FaceId']
        
        # 5. Add the new person to the DynamoDB Users table
        users_table = dynamodb.Table(TABLE_USER_NAME)
        users_table.put_item(
            Item={
                'FaceID': new_face_id,
                'Name': user_name,
                'Role': user_role,
                'CreatedAt': timestamp,
                'S3_ProfilePicturePath': image_key
            }
        )

        # 6. Return success response to Flutter
        return {
            'statusCode': 200,
            'headers': {'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({
                'message': 'Person added successfully',
                'face_id': new_face_id,
                'user_name': user_name,
                'role': user_role
            })
        }

    except Exception as e:
        print(f"Error adding new person: {str(e)}")
        return {
            'statusCode': 500,
            'headers': {'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({'error': 'Internal Server Error', 'details': str(e)})
        }